version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: ai-review-db
    environment:
      POSTGRES_USER: aireviewer
      POSTGRES_PASSWORD: aireviewer_password
      POSTGRES_DB: ai_review_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U aireviewer"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
